name: Check WordPress Update

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨检查更新
  workflow_dispatch: # 手动触发

permissions:
  contents: write

jobs:
  check-wordpress-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Fetch Latest WordPress Version
      id: fetch_version
      run: |
        LATEST_VERSION=$(wget -qO- "https://api.github.com/repos/WordPress/WordPress/tags" | grep '"name":' | head -1 | awk -F '"' '{print $4}')
        echo "Latest version: $LATEST_VERSION"
        echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

    - name: Download WordPress Latest
      run: |
        wget "https://github.com/WordPress/WordPress/archive/refs/tags/${LATEST_VERSION}.zip" -O "wordpress-${LATEST_VERSION}.zip"

    - name: Check if WordPress is Updated
      id: check_update
      run: |
        if [ -f wordpress-latest.zip ]; then
          if cmp -s wordpress-latest.zip "wordpress-${LATEST_VERSION}.zip"; then
            echo "WordPress is up to date."
            echo "update=false" >> $GITHUB_OUTPUT
          else
            echo "WordPress is updated."
            echo "update=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "No previous version detected. Treating as an update."
          echo "update=true" >> $GITHUB_OUTPUT
        fi

    - name: Save new version if updated
      if: steps.check_update.outputs.update == 'true'
      run: |
        mv "wordpress-${LATEST_VERSION}.zip" wordpress-latest.zip

    - name: Commit and Push Changes
      if: steps.check_update.outputs.update == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add wordpress-latest.zip
        git commit -m "Update WordPress to latest version: ${LATEST_VERSION}"
        git push origin HEAD
